FROM node:20.18.0-alpine

WORKDIR /app
RUN apk add --no-cache git
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build-storybook
EXPOSE 6006

FROM nginx:alpine

COPY --from=0 /app/storybook-static /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]